### ISSUE TITLE
Create a project folder structure(monerepo)

### ISSUE THREAD

**Issue by Nziranziza** [Kttle-Inc/Wishop#15]
Stack
- NestJs
- NextJs
- MongoDB
- Typeorm
- TailwindCSS

**Comment by pierratono** [comment]
@Musigwa and @Nziranziza 
What about this:

Stack
- NestJs
- NextJs
- MongoDB
- Mongoose
- TailwindCSS
- Swagger UI
- TanstackQuery (Replaicng tRPC approach)

**Comment by Musigwa** [comment]
@pierratono your suggestion’s great. Only that we may have struggles with trpc as we discussed in our last physical meeting. The rest is cool.

**Comment by pierratono** [comment]
Okay gonna keep rest then, just wanted to confirm 🫠

**Comment by Nziranziza** [comment]
> @Musigwa and @Nziranziza What about this:
> 
> Stack
> 
> * NestJs
> * NextJs
> * MongoDB
> * Mongoose
> * TailwindCSS
> * Swagger UI
> * tRPC ( with React TanstackQuery)

I think we avoided tRPC because we are thinking about having a mobile app and decided to go with traditional RestAPI architecture. I am also not a big fun of swagger UI, I think we could use POSTMAN to generate the api documentation and if we want to do something more we could look for other alternatives but swagger UI is just ugly 😂

**Comment by pierratono** [comment]
If you want to use postman you can simply import swagger ui generated json/yaml file man

So let's then use rest with tanstackquery insteadof trpc
